appName: REST API Villa
env: "development"
SECRET_KEY: "5|[.oClz;cx/{`SEvV=vJpgV5Qf`gfJY"
server:
  port: ":8080"
db:
  DB_HOST: "127.0.0.1"
  DB_USER:  "AGURA_24"
  DB_PASS:  ""
  DB_PORT:  5432
  DB_NAME:  "villa_db"
